### ISSUE TITLE
I’m interested in coming to Arctic JS

### ISSUE THREAD

**Issue by watson** [adventure-js/arcticjs.club#2] opened 2016-01-07 15:40 UTC
Arctic JS is a casual JS conference in the arctic circle organised by @feross, @mafintosh and @watson. 

**Location:** [Longyearbyen, Svalbard](https://www.google.com/maps/place/Longyearbyen,+Svalbard+and+Jan+Mayen/@72.6672124,-6.7662926,3z/data=!4m2!3m1!1s0x459c52d84f4557df:0xda86b2caa16495ec)
**Dates:** January 19-21, 2016 (we arrive on the 18th and leave on the 22nd)

Everyone is invited, but keep in mind that you're responsible for you own transport, [accommodation](https://github.com/watson/arcticjs.club/issues/5), food and polar-:bear:-attack-insurance. There is no formal schedule or speaker list and we'll make the rest up as we go :stuck_out_tongue_winking_eye: 

Leave a comment on this issue to be kept up to date with Arctic JS news and info.

You can also join the Freenode IRC channel **#arcticjs**
## :airplane: How to get there

Svalbard has a population of only 2000 people and is the most northern permanent human settlement in the world.

Normally the cheapest way to fly to Svalbard is to book two return flights:
1. From wherever you live, book a return ticket to **Oslo**
2. Book another return ticket from **Oslo** to **Longyearbyen** with [Norwegian](http://norwegian.com)

A good flight search engine is [Google Flights](https://flights.google.com).
## :hotel: Accommodation

Check out the [Shelter](https://github.com/watson/arcticjs.club/issues/5) issue.
## :warning: Stay safe

Svalbard will be experiencing [polar night](https://en.wikipedia.org/wiki/Polar_night), i.e. 24 hour darkness.

Bring warm clothing. It is currently -10º C, but January has gotten as cold as -40º C in the past. Be prepared.

If you go outside of the main settlement, you do so at your own risk. There are many potential dangers, including [polar bear attacks](http://www.telegraph.co.uk/news/worldnews/europe/norway/11483443/Tourist-in-Svalbard-during-solar-eclipse-mauled-by-polar-bear.html) and [avalanches](http://www.bbc.com/news/world-europe-35144236). If you stay in the main settlement, it's probably pretty safe. Be smart.

**Comment by imcaffrey** [comment] 2016-01-07 15:49
interesting --> interested?

**Comment by watson** [comment] 2016-01-07 15:59
@imcaffrey Ups - thanks :)

**Comment by feross** [comment] 2016-01-07 16:17
So far, we have 6 confirmed attendees. Maybe we can get a sponsor so we can bring in a some more speakers from far away!

**Comment by feross** [comment] 2016-01-07 16:19
Confirmed attendees:
1. @mafintosh 
2. @feross
3. @watson 
4. @jhiesey
5. @nealwu
6. @lpi
7. @whyrusleeping 
8. @diasdavid
9. @despairblue 
10. @dcposch
11. @RichardLitt 
12. @noffle
13. @copernicus-mogley

Leave a comment if you're coming, and we'll add you to the list.

**Comment by a0viedo** [comment] 2016-01-07 16:26
Great initiative! I would love to attend but it's kind of expensive flight from where I live (2k usd). Will wait for the videos, if any.

**Comment by joshmanders** [comment] 2016-01-07 16:31
Hi yes, first off, awesome website. Second if I get polar-🐻-attack-insurance does that allow me to cuddle all the bears I can up until attack?

**Comment by stelcheck** [comment] 2016-01-07 16:41
The more I search, the harder it gets, the higher my interest gets.

![screen shot 2016-01-08 at 1 41 01 am](https://cloud.githubusercontent.com/assets/592432/12176065/f4ca2562-b5a8-11e5-9bd2-220b37bd408c.png)

**Comment by mafintosh** [comment] 2016-01-07 16:46
@stelcheck try [flights.google.com](https://flights.google.com)

**Comment by mxstbr** [comment] 2016-01-07 20:01
Would love to come, but sadly can't afford it at the moment – if you manage to find a sponsor @feross, maybe we can work something out with speaking?

**Comment by RReverser** [comment] 2016-01-07 21:35
Wow, totally interested (in either attending or speaking), but not much time left to gather docs, apply for visa and flights are not cheap when buying only two weeks in advance. Are the dates 100% fixed or maybe could be moved further for more attendees to come?

**Comment by RReverser** [comment] 2016-01-07 21:38
Also, it would be much easier if it would be on the weekend to avoid need to lose even more vacation days...

**Comment by RichardLitt** [comment] 2016-01-08 01:05
I may be coming. Will decide after I sleep.

**Comment by whyrusleeping** [comment] 2016-01-08 01:24
I'm in, as well as @diasdavid

**Comment by asbjornenge** [comment] 2016-01-08 08:40
I :heart: this initiative! If I didn't have a little :baby: in the house I would come! When my kids are a little older... I'll bring them :wink: How about a [fjordjs.club](https://en.wikipedia.org/wiki/Lysefjord) next? :sunrise_over_mountains: :grin:

**Comment by watson** [comment] 2016-01-08 13:25
@RReverser you can always just work remotely when there - they might not notice. Visa shouldn't be an issue from the UK and there are cheap domestic flights from Oslo if you have a way to get there cheaply :wink:

**Comment by RReverser** [comment] 2016-01-08 13:28
> Visa shouldn't be an issue from the UK 

It is because I'm Ukrainian, so need a Schengen Visa first :)

**Comment by rhardih** [comment] 2016-01-08 13:30
Svalbard you say... :)

**Comment by despairblue** [comment] 2016-01-08 13:59
![gh](https://cloud.githubusercontent.com/assets/927609/12199411/49a73966-b618-11e5-8430-81c7e557c1d2.png)

See you there! Anyone in Oslo as early as me?

**Comment by despairblue** [comment] 2016-01-08 14:01
Also any tips about cheap accommodation in Longyearbyen? Like sharing a room or something.

**Comment by whyrusleeping** [comment] 2016-01-08 14:41
@despairblue I'm looking at getting an airbnb with four beds, and I have only three people in my group at this point. If youre interested, let me know

**Comment by despairblue** [comment] 2016-01-08 15:24
@whyrusleeping definitely am. I send request for a single bedroom on airbnb and asked someone on couch surfing. But if yours isn't outside of what I can afford I'm definitely interested.

**Comment by watson** [comment] 2016-01-08 20:14
@despairblue: Me, @feross, @mafintosh and a few other friends are flying to Oslo on the 17th. I think we are the same plane as you towards Longyearbyen on the 18th :smiley: We have an Airbnb in Oslo for the night

**Comment by dirad** [comment] 2016-01-08 20:45
i wanna come! anyone flying from Israel?

**Comment by feross** [comment] 2016-01-08 21:00
I can't believe how quickly this has become a real thing.

:beers: to the power of the internet for bringing people together!

**Comment by mafintosh** [comment] 2016-01-08 21:07
:beers: to polar bears and airplanes

**Comment by whyrusleeping** [comment] 2016-01-08 21:24
:beers: to aurora borealis and darkness

**Comment by FotoVerite** [comment] 2016-01-08 21:26
Do you have sponsorship for a photographer?

**Comment by feross** [comment] 2016-01-08 21:31
@FotoVerite Sent you an email.

**Comment by feross** [comment] 2016-01-08 21:31
Word has it that @dcposch of [scramble.io fame](https://blog.dcpos.ch/easy-email-encryption) may be coming... :+1: :+1: :+1:

**Comment by RichardLitt** [comment] 2016-01-08 21:42
Well. I am coming.

**Comment by feross** [comment] 2016-01-08 21:49
That brings the number to 11 confirmed attendees!

**Comment by watson** [comment] 2016-01-08 22:06
I've updated the issue description with info about cheap flights and accommodation :airplane: :hotel:

**Comment by hackergrrl** [comment] 2016-01-08 22:19
I'll be coming! :beers:

**Comment by feross** [comment] 2016-01-08 22:20
Wow - looking forward to finally meeting you!

If we get to 20 attendees, we will literally be 1% of the population of Svalbard which only has a population of 2000.

**Comment by rachelnicole** [comment] 2016-01-08 23:14
i'm hiding in @RichardLitt 's luggage.

**Comment by janecakemaster** [comment] 2016-01-08 23:14
damn im about to drop everything just go.. jag älskar sverige

**Comment by watson** [comment] 2016-01-08 23:21
@janecakemaster @dirad of cause you guys should come! Pro tip: To get cheap plane tickets, get to Oslo first and buy a separate ticket from Oslo to Longyearbyen

**Comment by janecakemaster** [comment] 2016-01-08 23:22
ohai @watson :wave: 
alas i probably wont but theres nothing like sweden in the dead of winter :skull: enjoy!!!

**Comment by watson** [comment] 2016-01-09 00:30
We've created an issue where you can coordinate room-sharing with other attendees: #5

**Comment by trygve-lie** [comment] 2016-01-09 00:39
Soooo... I started mentioning the idea of a conf at Svalbard four years ago after we started @webrebels. Think I've mentioned it to you a couple of times @mafintosh. So yes! I would love to attend. But dam it; January 19-21 2016. Way too short time for me to turn around and attend. Big sad polar bear here :(

**Comment by ralphtheninja** [comment] 2016-01-09 00:44
Hmm. Short notice but I'll give it some serious thought.

@0x00A @juliangruber @oleavr Up for a trip to Svalbard? :)

**Comment by mafintosh** [comment] 2016-01-09 00:46
@trygve-lie been excited about this idea ever since you first mentioned it. we could a summer themed one after webrebels in june as well. 24 hour sunlight!

**Comment by ralphtheninja** [comment] 2016-01-09 00:47
How cold is it this time of year?

**Comment by mafintosh** [comment] 2016-01-09 00:48
@ralphtheninja about -10C currently

**Comment by trygve-lie** [comment] 2016-01-09 01:15
A couple of things to keep in mind about Svalbard:

Yes; there are polar bears up there and they can be [dangerous](http://www.telegraph.co.uk/news/worldnews/europe/norway/11483443/Tourist-in-Svalbard-during-solar-eclipse-mauled-by-polar-bear.html). It is advised that you have [appropriate means of frightening and chasing off polar bears](http://www.sysselmannen.no/en/Shortcuts/Firearms/). 
They had a pretty bad [avalanche](http://www.bbc.com/news/world-europe-35144236) a couple of weeks ago so you might encounter the aftermath of that.

Its also worth noticing that Svalbard is _not_ part of the Schengen Area (which the mainland of Norway are). More [here](http://www.sysselmannen.no/en/Visitors/Entry-and-residence/) on what one need of visas and papers to go there.

> How cold is it this time of year?

Currently its mild up there. Just around [-10C](http://www.yr.no/place/Norway/Svalbard/Longyearbyen/) but it can be cold. Other parts of north of Norway did hit [-41C](http://www.nrk.no/finnmark/sprengkulde-i-nord_-vaknet-opp-til--41_-1.12737092) this week. So, it can be pretty cold. Dress warm.

On the bright side: europe's larges whiskey collection [in a bar](http://www.karlsbergerpub.no/) is up there. And the worlds most northern brewery (a craft brewery) did just [brew their first batch of polar beer](http://svalbardbryggeri.com/) up there.

Getting there can be done by flying:
- [Norwegian](https://www.norwegian.no/)
- [SAS](http://www.flysas.com/en/uk/)
- [Widerøe](http://www.wideroe.no/en)

Wikitravel's [guide on Svalbard](http://wikitravel.org/en/Svalbard) is worth reading.

**Comment by RReverser** [comment] 2016-01-09 01:18
Probably won't be able to attend this one due to mentioned issues, but question for the future trip (now that I learned about Svalbard I definitely want to get there):

http://www.bradtguides.com/destinations/polar-regions/svalbard/travel-and-visas.html and some other places say that you need "permission from the Sysselmann" for travelling in most of Svalbard, but I can't find any info on where and how this permission can be obtained.

Any advises from locals here?

**Comment by trygve-lie** [comment] 2016-01-09 01:18
@mafintosh o boy. yes. maybe we should look at one of [the boat trips](https://www.hurtigruten.com/find-a-trip/?id=121#destinations=1585&sort=recommended&asc=true) up there...

**Comment by trygve-lie** [comment] 2016-01-09 01:26
@RReverser Yes. That is true. 

Sysselmann is [The Govenor of Svalbard](http://www.sysselmannen.no/en/). Here [is detailed info](http://www.sysselmannen.no/en/Visitors/Planning-a-trip/) from Sysselmannen about who, where and what one need of permissions to travel around up there.

**Comment by terinjokes** [comment] 2016-01-09 01:28
Svalbard has been on my go-to list for a bit. Where are the confirmed attendees staying?

**Comment by mafintosh** [comment] 2016-01-09 01:32
@trygve-lie i'd be down for that :)

**Comment by copernicus-mogley** [comment] 2016-01-09 01:58
I can livestream and offer whatever other video support is needed!

**Comment by ralphtheninja** [comment] 2016-01-09 02:00
> @mafintosh o boy. yes. maybe we should look at one of the boat trips up there...

Those trips seems amazing! Quite costly though, but I'd imagine well worth it.

**Comment by trygve-lie** [comment] 2016-01-09 02:06
@ralphtheninja Yeah. They are costly :|

**Comment by ralphtheninja** [comment] 2016-01-09 02:10
> @ralphtheninja Yeah. They are costly :|

I wonder if there are boats with researchers as well. That could be a different entry point. Throw a bunch of crazy node developers in there :grinning:

**Comment by trygve-lie** [comment] 2016-01-09 02:13
@ralphtheninja Shit loads of research and science stuff up there. Not sure how much node they do though ;) It's more like [this stuff](https://www.croptrust.org/what-we-do/svalbard-global-seed-vault/).

Telenor is using Svalbard as a [test bed](http://www.telenor.com/media/articles/2014/svalbard-is-fibre-optics-test-bed/) for mobile and telecommunication things though.

**Comment by ralphtheninja** [comment] 2016-01-09 03:06
> @ralphtheninja Shit loads of research and science stuff up there. Not sure how much node they do though ;) It's more like this stuff.

Aah yeah I thought more of spending time with them to build tools, or showing tools like dat etc.

**Comment by ralphtheninja** [comment] 2016-01-09 03:11
@trygve-lie Oh wow, did you see that interactive thing? You can walk around and check it out :)

**Comment by iancrowther** [comment] 2016-01-09 03:37
Researching...

**Comment by AlicanC** [comment] 2016-01-09 04:30
Damn, it is impossible to get a visa on such a short notice. A great and adventurous event nonetheless. I hope I can make it to the next one. Have fun!

**Comment by whyrusleeping** [comment] 2016-01-09 05:38
my airbnb is full, more people from my company coming. @RichardLitt wooo!

**Comment by gsans** [comment] 2016-01-09 11:33
Oh Wow! This sounds like a great idea. Shame I noticed too late. I can try to get funds from Google Experts Program. "Bear" with me! 😊

**Comment by yangwao** [comment] 2016-01-09 13:10
Interested in summer edition as well :D but I can't find any good _cheap_ flights, [tops up over 1k+ and two stops](https://www.google.com/flights/#search;f=VIE,XWW;t=LYR;d=2016-01-17;r=2016-01-22;sel=VIEARN0OS317-ARNOSL1SK843-OSLTOS1SK4414-TOSLYR1SK4414)
But I'd join and watch some livestream if so! :) 
My current interest rate is in 40%, but I still could buy in and start looking for accomodation there :D

**Comment by feross** [comment] 2016-01-09 13:16
@yangwao What about buying a flight to Oslo, then Longyearbyen separately?

https://www.google.dk/flights/#search;f=VIE,XWW;t=OSL;d=2016-01-17;r=2016-01-22
https://www.google.dk/flights/#search;f=OSL;t=LYR;d=2016-01-18;r=2016-01-22

Saves you 1300kr!

**Comment by yangwao** [comment] 2016-01-09 13:49
@feross yeah, thanks! @watson is trying convince me to go! I'll made final decision on 10.1., because I'm organizing second NodeSchool Bratislava on 23. it will be little harder for me :)
My current interest rate is at 55% :D

**Comment by forrestlin** [comment] 2016-01-11 04:47
If anyone is lamenting flight prices, I do flight hacking for a living, so please feel free to reach out.

I also spent a week in Longyearbyen last spring for the solar eclipse, so I'd be happy to field any questions regarding life in the northernmost city (town?) in the world. Polar bears are indeed a real threat - there was an attack on a tourist during my stay - and you should take all warnings very seriously.

**Comment by trodrigues** [comment] 2016-01-11 08:24
Damn, I would love to get in on this, and in Berlin I'm not even that far away, but it's very short notice. Hope there's more in the future :)

**Comment by watson** [comment] 2016-01-11 10:04
@forrestlin Thanks :smiley: So far the best "hack" we've found was to by a return ticket from wherever you are to Oslo. Then by a separate return ticket from Oslo to Longyearbyen - possibly staying one night in Oslo. That for some reason is way cheeper than buying a return directly to Longyearbyen.

**Comment by fbaiodias** [comment] 2016-01-15 15:51
I'm going too! :smiley::snowflake:

**Comment by iancrowther** [comment] 2016-01-15 17:15
no can do :-( will be there in the summer

**Comment by despairblue** [comment] 2016-01-15 18:35
Anyone already in Oslo?

**Comment by hackergrrl** [comment] 2016-01-15 18:50
@despairblue: I get into OSL at 1630h today! I think @RichardLitt gets in a bit earlier?

**Comment by despairblue** [comment] 2016-01-15 18:56
@noffle that is your local time, right? Asking since it is already 1955 in olso :D

**Comment by hackergrrl** [comment] 2016-01-15 19:17
@despairblue: whoops! I meant Oslo time, but I guess that makes it 1630h **tomorrow**. :D

**Comment by trygve-lie** [comment] 2016-01-15 21:04
If anyone has a stop over in Oslo traveling to or from: Let me know and I will be more than happy to help with anything and join for a beer or dinner.

Our guest room is also free if anyone need a place to crash for a night. We're 4 min from Oslo Central station.

**Comment by watson** [comment] 2016-01-15 21:37
@despairblue did you find a place to stay in Oslo or are you still just sleeping in the airport? Check @trygve-lie's comment above :smiley:

**Comment by trygve-lie** [comment] 2016-01-15 21:48
@despairblue let me know if u need a place to crash. Happy to help :-)

**Comment by despairblue** [comment] 2016-01-15 23:30
@trygvw-lie @watson thanks I booked something via AirBnB already, next to grünerløkka. we're going out for a beer now. I suppose it's too late for you, right?

**Comment by trygve-lie** [comment] 2016-01-15 23:40
@despairblue A tad late now. How long are you in town?

**Comment by RichardLitt** [comment] 2016-01-16 01:01
@trygve-lie If the offer is open, I'm coming back from Svalbard on the 22nd and have a night where I haven't booked anything yet, as I'm heading to Iceland the next day. I would be super appreciative! :D

**Comment by trygve-lie** [comment] 2016-01-16 01:24
@RichardLitt Offer is open :-) I'll have the guest room ready for you.

**Comment by hackergrrl** [comment] 2016-01-16 10:37
I'm in the same boat as Richard (in Oslo for the night of the 22nd). Do you
still have space / are near the central station?

**Comment by RichardLitt** [comment] 2016-01-16 12:40
@trygve-lie :D awesome! Thank you!

**Comment by despairblue** [comment] 2016-01-16 14:18
@trygve-lie sorry, I don't have any internet when I'm out. We could meet today somewhere with @noffle and @RichardLitt.

**Comment by RichardLitt** [comment] 2016-01-16 14:26
Yep! I'm around. Maybe we should just chat in freenode #arcticjs?

**Comment by copernicus-mogley** [comment] 2016-01-16 17:39
Preparing for the livestreams. Is there any kind of rough schedule for presentations? Maybe a start time for a welcome address or something? Anything else happening that someone might want streamed?
I'm totally open to comments and suggestions from the people attending and those who are not so lucky.

**Comment by mariusGundersen** [comment] 2016-01-16 22:59
This must be the js conference with the shortest preparation time! I can't join at such short notice, but if anyone are up for a subarcticJS while they stop over in Oslo, I'll join!

**Comment by hackergrrl** [comment] 2016-01-17 09:18
@mariusGundersen: me and @RichardLitt and @despairblue (at least) are in Oslo today! Up for getting together to do some hacking later on today if you're already in town. :)

**Comment by feross** [comment] 2016-01-17 09:27
Nice, we land in 15 minutes.

**Comment by mariusGundersen** [comment] 2016-01-17 11:34
I suggest we meet up at Kulturhuset, which is pretty much city center, and is a great place for coffee, beer and hacking.

**Comment by mariusGundersen** [comment] 2016-01-17 11:40
BTW, for those who are in Oslo today, you should head over to the royal castle, as the royal family is celebrating their 25th year of reign.

**Comment by copernicus-mogley** [comment] 2016-01-17 16:10
What's the address of the place we're meeting in Svalbard tomorrow?

**Comment by RichardLitt** [comment] 2016-01-17 17:18
I'm not sure we have something set in stone yet.

**Comment by ralphtheninja** [comment] 2016-01-17 19:40
> What's the address of the place we're meeting in Svalbard tomorrow?

The address is Svalbard :grinning:

**Comment by despairblue** [comment] 2016-01-17 20:25
[here](http://www.tripadvisor.com/Restaurant_Review-g503715-d4298098-Reviews-Karlsberger_Pub-Longyearbyen_Spitsbergen_Svalbard.html)? :smile:

**Comment by ralphtheninja** [comment] 2016-01-18 12:34
Please post any updates here or on another issue when you are starting up. Not everyone uses twitter ;)

**Comment by mafintosh** [comment] 2016-01-18 13:16
We just landed. We wanted to walk from the airport but was told it was part of the unsafe zone (:bear:) so now we're on a bus

**Comment by ralphtheninja** [comment] 2016-01-18 13:52
> We just landed. We wanted to walk from the airport but was told it was part of the unsafe zone (:bear:) so now we're on a bus

lol

**Comment by copernicus-mogley** [comment] 2016-01-20 21:35
Posted some pics of Longyearbyen that I took on Tuesday ... http://ipfs.alexandria.media/ipfs/QmSnEvxUSSJeMfmA4dqkhti9tJRY9f1CzuLrYVLN1DrFVm/content/index.html

**Comment by hackergrrl** [comment] 2016-01-21 00:53
Awesome photos! I took a few as well of the northern lights:

http://www.stephenwhitmore.com/tmp/longyearbyen.JPG
http://www.stephenwhitmore.com/tmp/lights1.JPG
http://www.stephenwhitmore.com/tmp/lights2.JPG
http://www.stephenwhitmore.com/tmp/lights3.JPG

**Comment by copernicus-mogley** [comment] 2016-01-21 16:38
Great shots @noffle
Here are some more that I took yesterday: http://ipfs.alexandria.media/ipfs/QmeWz9YZEeNFXQhHg4PnR5ZiNr5isttgi5n1tc1eD5EfGU/content/index.html

**Comment by trygve-lie** [comment] 2016-01-21 16:48
@RichardLitt when do you arrive in Oslo tomorrow?

@noffle sorry for my late reply. Busy week. Sadly we are still renovating parts of our apt so we don't really have comfortable room for more than one person or one couple (we have just one extra double bed in a pretty tiny but cosy room at the moment).

**Comment by RichardLitt** [comment] 2016-01-21 16:58
@trygve-lie Around 3:30, and I'll get a train into the city, so... around 5:00? Where should I head? Thanks so much! Are you keen on hanging out? :D

**Comment by hackergrrl** [comment] 2016-01-21 17:13
@trygve-lie: how far are you from Oslo central station? I can sleep on the floor if there's space.

**Comment by copernicus-mogley** [comment] 2016-01-21 18:35
http://localhost:8080/ipfs/QmZbgfddJfXdSwbv4vm2auDoomfhEFmNnQpqTmZ5Bpherv

**Comment by watson** [comment] 2016-01-21 18:47
@copernicus-mogley localhost?

**Comment by copernicus-mogley** [comment] 2016-01-21 18:47
HAHA! That killed the wifi here. We were testing local IPFS usage.

**Comment by copernicus-mogley** [comment] 2016-01-21 18:49
Gateway access == http://ipfs.alexandria.media/ipfs/QmZbgfddJfXdSwbv4vm2auDoomfhEFmNnQpqTmZ5Bpherv

**Comment by trygve-lie** [comment] 2016-01-21 21:09
@noffle: had a quick check here with my misses and we'll make some space for you :) 

@noffle @RichardLitt do you both arrive at the same time tomorrow? I can meet you at Oslo S. We are two sub stops from Oslo S (10 minutes to walk).

**Comment by hackergrrl** [comment] 2016-01-21 21:13
@trygve-lie: I ended up making other arrangements, but thank you anyways. :)

**Comment by RichardLitt** [comment] 2016-01-21 22:11
Yeah, we do! I'll let you know when we're on the train and headed in. Should I post here, or are you on IRC?

**Comment by feross** [comment] 2016-01-21 22:55
Nice shots guys!

**Comment by trygve-lie** [comment] 2016-01-22 07:50
@RichardLitt At Oslo S there is a coffee bar named Steam. Its next to the Oslo Visitor Center. I will be there at 17:00. Look for a laptop with a "WebRebels" sticker on it. I've also sent you an email (the email form your github account) with my phone number etc.

@noffle Sorry for my late replies to this. Was a bit back and forth here on how we could house people. Though; feel free to cancel any other arrangements you have made. You are more than welcome to stay for free.

**Comment by RichardLitt** [comment] 2016-01-22 10:18
@trygve-lie Sounds good! I will see you there. :D

**Comment by dcposch** [comment] 2016-01-22 10:31
ill be at Steam also!

**Comment by RichardLitt** [comment] 2016-01-22 10:58
Should we... close this issue?

**Comment by mafintosh** [comment] 2016-01-22 11:56
![img](http://i.imgur.com/tgAYMLd.jpg)

**Comment by despairblue** [comment] 2016-01-23 16:14
second that, but it was ![fantastic](https://media.giphy.com/media/fxWH1Uu8sZmCs/giphy.gif)

**Closed as completed** 2017-02-20 16:40 UTC
